server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    response-cache-auto-expiration-in-seconds:5
    use-read-only-response-cache:false
    enableSelfPreservation:false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eurka-server



